version: 2.1

jobs:
  run-tests:
    machine:
      image: ubuntu-2204:2022.10.2
    steps:
      - checkout
      - run: |
          docker run -it --rm -v $PWD:$PWD -w $PWD -v /var/run/docker.sock:/var/run/docker.sock mcr.microsoft.com/playwright/java:v1.28.1-focal ./gradlew test --debug
          mkdir -p ~/test-results/junit/
          find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit
  publish-docker-image:
    docker:
      - image: docker:20.10.18-git
    environment:
      IMAGE_TAG: ghcr.io/robertograham/departure-tests:latest
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.18
      - run: |
          docker login ghcr.io -u RobertoGraham -p $PERSONAL_ACCESS_TOKEN
          docker build -t $IMAGE_TAG .
          docker push $IMAGE_TAG

workflows:
  release:
    jobs:
      - run-tests:
          filters:
            branches:
              ignore: master
      - publish-docker-image:
          filters:
            branches:
              only: master
